# frozen_string_literal: true
source "https://rubygems.org"

gem "sinatra-activerecord"
gem "activerecord", "~>5.2", :require => "active_record"
gem "sqlite3"
gem "pry"
gem "require_all"
gem "rake"
gem "faker"
gem "tty-prompt"
gem "tty-box"
gem "pastel"
gem "tty-color-cli"
gem "gemoji"
gem "tty-screen"
gem "giphy"
# gem "catpix"
# gem "rmagick"